let products = [
    {
        id: 0,
        category: 'sushi',
        image: './images/product1.png',
        title: 'Филадельфия Смоук',
        desc: "Лосось копченый, курица копченая, омлет, огурец, авокадо, сыр, микс соусов, 6 шт.",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 1,
        category: 'sushi',
        image: './images/product2.png',
        title: 'Калифорния',
        desc: "Краб, авокадо, огурец, тобико, 6 шт.",
        price: 42000,
        numberOfItems: 0,
    },
    {
        id: 2,
        category: 'sushi',
        image: './images/product3.png',
        title: 'Филадельфия Нисуаз',
        desc: "Угорь, авокадо, сыр, тобико, соус «Нисуаз», кунжут, 6 шт.",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 3,
        category: 'sushi',
        image: './images/product4.png',
        title: 'Калифорния Дрим',
        desc: "Креветка, авокадо, краб-микс, сыр, соус «Спайси манго», тобико, кунжут, 6 шт.",
        price: 43000,
        numberOfItems: 0,
    },
    {
        id: 4,
        category: 'sushi',
        image: './images/product5.png',
        title: 'Имбирный лосось',
        desc: "Лосось опаленный, гуакамоле, сыр, имбирно-апельсиновый дрессинг, стружка тунца, зеленый лук, 6 шт.",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 5,
        category: 'sushi',
        image: './images/product6.png',
        title: 'Сицилийский',
        desc: "Лосось, авокадо, креветка, сыр, острый соус «Спайси манго», 6 шт.",
        price: 42000,
        numberOfItems: 0,
    },
    {
        id: 6,
        category: 'sushi',
        image: './images/product7.png',
        title: 'Орандж Краб',
        desc: "Снежный краб, авокадо, сыр, микс соусов, хрустящая маменори, 6 шт.",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 7,
        category: 'sushi',
        image: './images/product8.png',
        title: 'Калифорния Хот',
        desc: "Микс краба, авокадо, огурец, тобико, 6 шт.",
        price: 48000,
        numberOfItems: 0,
    },
    {
        id: 8,
        category: 'salads',
        image: './images/product9.png',
        title: 'Говядина со спаржей',
        desc: "Говядина, спаржа, руккола, авокадо, томаты черри, соус «Кальби», кинза, кунжут.",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 9,
        category: 'salads',
        image: './images/product10.png',
        title: 'Цезарь с креветками',
        desc: "Креветки, сыр, салат романо, салат айсберг, гренки, соус «Цезарь»",
        price: 42000,
        numberOfItems: 0,
    },
    {
        id: 10,
        category: 'salads',
        image: './images/product11.png',
        title: 'Феншуй',
        desc: "Острые креветки темпура, салатный микс, перец, кунжут, авокадо, харумаки.",
        price: 39000,
        numberOfItems: 0,
    },
    {
        id: 11,
        category: 'salads',
        image: './images/product12.png',
        title: 'Кумотори',
        desc: "Креветки, листья салата мангольд, авокадо, томаты, соусы «Унаги» и «Нисуаз».",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 12,
        category: 'salads',
        image: './images/product13.png',
        title: 'Кофу',
        desc: "Жареные баклажаны, томаты, чеснок, кинза, соус «Свит чили».",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 13,
        category: 'salads',
        image: './images/product14.png',
        title: 'Сендай',
        desc: "Креветки, листья салата, тобико, пикантный соус.",
        price: 42000,
        numberOfItems: 0,
    },
    {
        id: 14,
        category: 'salads',
        image: './images/product15.png',
        title: 'Цезарь с курицей',
        desc: "Курица, сыр, салат романо, салат айсберг, гренки, соус «Цезарь»",
        price: 39000,
        numberOfItems: 0,
    },
    {
        id: 15,
        category: 'salads',
        image: './images/product16.png',
        title: 'Авокадо Хот',
        desc: "Печеный авокадо, тофу, томаты, перечный соус",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 16,
        category: 'soups',
        image: './images/product17.png',
        title: 'Ими Том-Ям',
        desc: "Кокосовое молоко, шампиньоны, вешенки, шимиджи, галангал, лайм, лимонник.",
        price: 35000,
        numberOfItems: 0,
    },
    {
        id: 17,
        category: 'soups',
        image: './images/product18.png',
        title: 'Суп с говядиной чили',
        desc: "Говядина, пшеничная лапша, шампиньоны, перец чили, перепелиное яйцо.",
        price: 30000,
        numberOfItems: 0,
    },
    {
        id: 18,
        category: 'soups',
        image: './images/product19.png',
        title: 'Тануки Ям',
        desc: "Креветки, мидии, кальмар, гребешок, кокосовое молоко, шампиньоны, лимонник.",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 19,
        category: 'soups',
        image: './images/product20.png',
        title: 'Чикен Чиз',
        desc: "Копченая курица, сыр, бекон, томаты черри, шампиньоны.",
        price: 29000,
        numberOfItems: 0,
    },
    {
        id: 20,
        category: 'soups',
        image: './images/product21.png',
        title: 'Суп с Лосесем',
        desc: "Лосось, рис, водоросли, кунжут, нори.",
        price: 38000,
        numberOfItems: 0,
    },
    {
        id: 21,
        category: 'soups',
        image: './images/product22.png',
        title: 'Азиатский суп с говядиной',
        desc: "Говядина, шпинат, омлет, нори, кинза, кунжут, яичная лапша",
        price: 35000,
        numberOfItems: 0,
    },
    {
        id: 22,
        category: 'soups',
        image: './images/product23.png',
        title: 'Рамен с Курицей',
        desc: "Курица, яичная лапша, грибы эноки, пак-чой.",
        price: 39000,
        numberOfItems: 0,
    },
    {
        id: 23,
        category: 'soups',
        image: './images/product24.png',
        title: 'Том Кха',
        desc: "Курица, кокосовое молоко, яйцо, грибы.",
        price: 48000,
        numberOfItems: 0,
    },
    {
        id: 24,
        category: 'hotter',
        image: './images/product25.png',
        title: 'Дарада Самбал',
        desc: "Дорада, мини-картофель, томаты черри, брокколи, соус самбал, лайм, имбирь, кунжут.",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 25,
        category: 'hotter',
        image: './images/product26.png',
        title: 'Медальон Кальби',
        desc: "Говядина, картофельное пюре с васаби, спаржа, соус «Кальби», кунжут.",
        price: 45000,
        numberOfItems: 0,
    },
    {
        id: 26,
        category: 'hotter',
        image: './images/product27.png',
        title: 'Кальмар Свит-Чили',
        desc: "Кальмар, баклажан, брокколи, томаты, кинза, кунжут, соусы «Кальби» и «Свит чили»",
        price: 42000,
        numberOfItems: 0,
    },
    {
        id: 27,
        category: 'hotter',
        image: './images/product28.png',
        title: 'Лапша Самбал бали',
        desc: "Креветки, листья салата мангольд, авокадо, томаты, соусы «Унаги» и «Нисуаз».",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 28,
        category: 'hotter',
        image: './images/product29.png',
        title: 'Фунчоза с креветками',
        desc: "Креветки, маринованный бамбук, морковь, перец чили, грибы, острый соус, стеклянная лапша.",
        price: 44000,
        numberOfItems: 0,
    },
    {
        id: 29,
        category: 'hotter',
        image: './images/product30.png',
        title: 'Лапша с морепродуктами',
        desc: "Кальмар, креветки, овощи, грибы шиитаке, кунжут, лапша удон,",
        price: 40000,
        numberOfItems: 0,
    },
    {
        id: 30,
        category: 'hotter',
        image: './images/product31.png',
        title: 'Утка по Пекински',
        desc: "Запечённая утка, маринованная в саке и пряностях, соус «Хойсин», пшеничные блинчики, 7 шт.",
        price: 48000,
        numberOfItems: 0,
    },
    {
        id: 31,
        category: 'hotter',
        image: './images/product32.png',
        title: 'Семга на гриле',
        desc: "Стейк из семги, кислосладкий соус, овощи, мини-картофель.",
        price: 35000,
        numberOfItems: 0,
    },
    {
        id: 32,
        category: 'dietary',
        image: './images/product33.png',
        title: 'Овощи Теппан',
        desc: "Цукини, баклажаны, перец, морковь, шампиньоны, ростки сои, лук, кунжут",
        price: 30000,
        numberOfItems: 0,
    },
    {
        id: 33,
        category: 'dietary',
        image: './images/product34.png',
        title: 'Киноа',
        desc: "Грибы шиитаке, авокадо, баклажан, киноа, перец гриль, руккола, 6 шт.",
        price: 25000,
        numberOfItems: 0,
    },
    {
        id: 34,
        category: 'dietary',
        image: './images/product35.png',
        title: 'Овощи',
        desc: "С овощами, грибами и бамбуком (8 шт.) + соус «Шогояки» и соус «Кохаку».",
        price: 21000,
        numberOfItems: 0,
    },
    {
        id: 35,
        category: 'dietary',
        image: './images/product36.png',
        title: 'Чука с ореховым соусом',
        desc: "Чука, ореховый соус.",
        price: 22000,
        numberOfItems: 0,
    },
    {
        id: 36,
        category: 'dietary',
        image: './images/product37.png',
        title: 'Авокадо Хот',
        desc: "Цукини, баклажаны, перец, морковь, шампиньоны, ростки сои, лук, кунжут",
        price: 24000,
        numberOfItems: 0,
    },
    {
        id: 37,
        category: 'dietary',
        image: './images/product38.png',
        title: 'Эдамаме Салт',
        desc: "Бобы, морская соль.",
        price: 31000,
        numberOfItems: 0,
    },
    {
        id: 38,
        category: 'dietary',
        image: './images/product39.png',
        title: 'Эдамаме Чили',
        desc: "Бобы, острый соус чили.",
        price: 30000,
        numberOfItems: 0,
    },
    {
        id: 39,
        category: 'dietary',
        image: './images/product40.png',
        title: 'Вегатарианский сет',
        desc: "Ролл с огурцом - 1 (6 шт.) Ролл с авокадо - 1 (6 шт.) Гункан Чука - 5 шт. Суши Авокадо - 3 шт. Киноа ролл - 1 (6 шт.)",
        price: 48000,
        numberOfItems: 0,
    },
]